# coding=utf-8
"""
Django settings for djRefugioAnimalesClient project.

Generated by 'django-admin startproject' using Django 1.8.19.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import environ
import os

from djRefugioAnimalesClient.core.providers import RefugioAnimalesProvider
from djRefugioAnimalesClient.core.providers.refugio_animales.auth.OAuth2Authentication import OAuthGranTypes

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    DJREFUGIOANIMALES_API_SERVER=(str, 'token_auth_server'),

    DJREFUGIOANIMALES_SERVER_TOKEN_AUTH_HOST=(str, 'http://127.0.0.1'),
    DJREFUGIOANIMALES_SERVER_TOKEN_AUTH_PORT=(int, 8010),
    DJREFUGIOANIMALES_SERVER_TOKEN_AUTH_TRY_AUTH_IN_TOKEN_FAIL=(bool, False),

    DJREFUGIOANIMALES_SERVER_JWT_HOST=(str, 'http://127.0.0.1'),
    DJREFUGIOANIMALES_SERVER_JWT_PORT=(int, 8011),
    DJREFUGIOANIMALES_SERVER_JWT_TRY_AUTH_IN_TOKEN_FAIL=(bool, False),

    DJREFUGIOANIMALES_SERVER_OAUTH_HOST=(str, 'http://127.0.0.1'),
    DJREFUGIOANIMALES_SERVER_OAUTH_PORT=(int, 8012),
    DJREFUGIOANIMALES_SERVER_OAUTH_GRANT_TYPE=(str, OAuthGranTypes.CLIENT_CREDENTIALS),
)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Take environment variables from .env file
server_env = os.environ.get('PYTHON_ENV', 'development')
environ.Env.read_env(os.path.join(BASE_DIR, '.environments/.env.{server_env}'.format(server_env=server_env)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.refugio_animales'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'djRefugioAnimalesClient.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'djRefugioAnimalesClient/templates'),
            os.path.join(BASE_DIR, 'apps.refugio_animales/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djRefugioAnimalesClient.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static/'


# https://docs.djangoproject.com/en/3.2/ref/contrib/messages/
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG:   'alert-info',
    messages.INFO:    'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR:   'alert-danger',
}

DJREFUGIOANIMALES = {
    # Indica al proyecto que configuración tomar dentro de 'DJREFUGIOANIMALES.servers'
    'default_server': env('DJREFUGIOANIMALES_API_SERVER'),

    # Establece los servidores disponibles para la API de Refugio de animales y las credenciales de acceso para la
    # autentificación
    'servers': {
        'token_auth_server': {
            # Host del servidor de la API de Refugio de Animales
            'host': env('DJREFUGIOANIMALES_SERVER_TOKEN_AUTH_HOST'),
            # Puerto del servidor de la API de Refugio de Animales
            'port': env('DJREFUGIOANIMALES_SERVER_TOKEN_AUTH_PORT'),

            # Username para realizar la autentificación y obtener el access_token haciendo uso también del 'password'
            'username': env('DJREFUGIOANIMALES_SERVER_TOKEN_AUTH_USERNAME'),
            # Password para realizar la autentificación y obtener el access_token haciendo uso también del 'username'
            'password': env('DJREFUGIOANIMALES_SERVER_TOKEN_AUTH_PASSWORD'),

            # [OPCIONAL] Cuando se especifica un 'access_token' se usara para realizar la autentificación en lugar de
            # usar el 'username' y 'password'
            'access_token': env('DJREFUGIOANIMALES_SERVER_TOKEN_AUTH_ACCESS_TOKEN'),

            # [OPCIONAL] Cuando el 'access_token' es incorrecto se fuerza a intentar en realizar la autentificación por
            # 'username' y 'password'
            # Por default su valor es False
            'try_auth_in_token_fail': env('DJREFUGIOANIMALES_SERVER_TOKEN_AUTH_TRY_AUTH_IN_TOKEN_FAIL'),
        },
        'jwt_server': {
            # Host del servidor de la API de Refugio de Animales
            'host': env('DJREFUGIOANIMALES_SERVER_JWT_HOST'),
            # Puerto del servidor de la API de Refugio de Animales
            'port': env('DJREFUGIOANIMALES_SERVER_JWT_PORT'),

            # Username para realizar la autentificación y obtener el access_token haciendo uso también del 'password'
            'username': env('DJREFUGIOANIMALES_SERVER_JWT_USERNAME'),
            # Password para realizar la autentificación y obtener el access_token haciendo uso también del 'username'
            'password': env('DJREFUGIOANIMALES_SERVER_JWT_PASSWORD'),

            # [OPCIONAL] Cuando se especifica un 'access_token' se usara para realizar la autentificación en lugar de
            # usar el 'username' y 'password'
            'access_token': env('DJREFUGIOANIMALES_SERVER_JWT_ACCESS_TOKEN'),
            # [OPCIONAL] Cuando se especifica un 'refresh_token' se usara para realizar el refresh del 'access_token'
            'refresh_token': env('DJREFUGIOANIMALES_SERVER_JWT_REFRESH_TOKEN'),

            # [OPCIONAL] Cuando el 'access_token' y 'refresh_token' son incorrectos se fuerza a intentar en realizar la
            # autentificación por 'username' y 'password'
            # Por default su valor es False
            'try_auth_in_token_fail': env('DJREFUGIOANIMALES_SERVER_JWT_TRY_AUTH_IN_TOKEN_FAIL'),
        },
        'oauth_server': {
            # Host del servidor de la API de Refugio de Animales
            'host': env('DJREFUGIOANIMALES_SERVER_OAUTH_HOST'),
            # Puerto del servidor de la API de Refugio de Animales
            'port': env('DJREFUGIOANIMALES_SERVER_OAUTH_PORT'),

            # Indica el flujo de OAuth, si no se especifica por default se usara client_credentials
            'grant_type': env('DJREFUGIOANIMALES_SERVER_OAUTH_GRANT_TYPE'),
            # Client_id de la aplicación registrada en la API de Refugio de Animales para realizar la autorización
            # utilizando los flujos de OAuth 2.0
            'client_id': env('DJREFUGIOANIMALES_SERVER_OAUTH_CLIENT_ID'),
            # Client_secret de la aplicación registrada en la API de Refugio de Animales para realizar la
            # autorización utilizando los flujos de OAuth 2.0
            'client_secret': env('DJREFUGIOANIMALES_SERVER_OAUTH_CLIENT_SECRET'),

            # [OPCIONAL] Username del usuario registrado en la API de Refugio de Animales para realizar la autorización
            # mediante el Resource Owner Password Grant
            'username': env('DJREFUGIOANIMALES_SERVER_OAUTH_USERNAME'),
            # [OPCIONAL] Password del usuario registrado en la API de Refugio de Animales para realizar la autorización
            # mediante el Resource Owner Password Grant
            'password': env('DJREFUGIOANIMALES_SERVER_OAUTH_PASSWORD'),
        },
    },
}

# region Singleton
RefugioAnimalesProvider()
# endregion
